apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: course-app-id
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"